version: '3.7'

services:
  database:
    image: postgres
    container_name: database-carrental-api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=carrentalapi
      - POSTGRES_PASSWORD=carrentalapi
      - POSTGRES_DB=carrentalapi
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: carrental-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local